language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
